version: '3.1'
services:
  db:
    image: mongo
    container_name: "mongo"
    command: 
      - mongod
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
  backend:
    build: 
      context: ./backend/
      dockerfile: Dockerfile
    container_name: "express-server"
    ports:
      - 3000:3000
    depends_on:
      - db
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: "client"
    ports:
      - 8080:3000
    volumes:
      - ./frontend:/usr/src/app
    command: "npm start"